# Generated by Django 5.0 on 2023-12-12 21:34

import django.core.validators
import django.db.models.deletion
import minecraft_mod_downloader.models._mem_db_core.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minecraft_version', models.CharField(max_length=9, validators=[minecraft_mod_downloader.models._mem_db_core.models.validators.UnsanitisedMinecraftVersionValidator(), django.core.validators.MinLengthValidator(3)], verbose_name='Minecraft Version')),
                ('mod_loader', models.CharField(choices=[('FO', 'Forge'), ('FA', 'Fabric'), ('QU', 'Quilt')], max_length=2, verbose_name='Mod Loader')),
                ('_unique_identifier', models.CharField(max_length=30, validators=[minecraft_mod_downloader.models._mem_db_core.models.validators.UniqueIdentifierValidator(), django.core.validators.MinLengthValidator(2)], verbose_name='Unique Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='ModTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[minecraft_mod_downloader.models._mem_db_core.models.validators.TagNameValidator(), django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Mod Tag',
            },
        ),
        migrations.CreateModel(
            name='DetailedMod',
            fields=[
                ('basemod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='_mem_db_core.basemod')),
                ('name', models.CharField(max_length=30, unique=True, validators=[minecraft_mod_downloader.models._mem_db_core.models.validators.UniqueIdentifierValidator(), django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('version_id', models.CharField(max_length=8, validators=[minecraft_mod_downloader.models._mem_db_core.models.validators.ShortIDValidator(), django.core.validators.MinLengthValidator(2)], verbose_name='Version ID')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
            ],
            bases=('_mem_db_core.basemod',),
        ),
        migrations.CreateModel(
            name='SimpleMod',
            fields=[
                ('basemod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='_mem_db_core.basemod')),
            ],
            options={
                'verbose_name': 'Simple Mod',
            },
            bases=('_mem_db_core.basemod',),
        ),
        migrations.AddConstraint(
            model_name='basemod',
            constraint=models.UniqueConstraint(fields=('minecraft_version', 'mod_loader', '_unique_identifier'), name='unique_identifier_per_environment'),
        ),
        migrations.CreateModel(
            name='APISourceMod',
            fields=[
                ('detailedmod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='_mem_db_core.detailedmod')),
                ('api_source', models.CharField(choices=[('CF', 'CurseForge'), ('MR', 'Modrinth')], max_length=2, verbose_name='API Source')),
                ('api_mod_id', models.CharField(max_length=8, validators=[minecraft_mod_downloader.models._mem_db_core.models.validators.ShortIDValidator(), django.core.validators.MinLengthValidator(2)], verbose_name='API Mod ID')),
            ],
            options={
                'verbose_name': 'API Source Mod',
            },
            bases=('_mem_db_core.detailedmod',),
        ),
        migrations.CreateModel(
            name='CustomSourceMod',
            fields=[
                ('detailedmod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='_mem_db_core.detailedmod')),
                ('download_url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Download URL')),
            ],
            options={
                'verbose_name': 'Custom Source Mod',
            },
            bases=('_mem_db_core.detailedmod',),
        ),
        migrations.AddField(
            model_name='detailedmod',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mods', to='_mem_db_core.modtag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='apisourcemod',
            constraint=models.UniqueConstraint(fields=('api_mod_id', 'api_source'), name='unique_api_mod_id_per_api_source'),
        ),
        migrations.AddConstraint(
            model_name='apisourcemod',
            constraint=models.UniqueConstraint(fields=('api_mod_id', 'detailedmod_ptr'), name='unique_api_mod_id_per_unique_identifier'),
        ),
        migrations.AddConstraint(
            model_name='detailedmod',
            constraint=models.UniqueConstraint(fields=('version_id', 'name'), name='unique_version_id_per_name'),
        ),
        migrations.AddConstraint(
            model_name='detailedmod',
            constraint=models.UniqueConstraint(fields=('version_id', 'basemod_ptr'), name='unique_version_id_per_unique_identifier'),
        ),
        migrations.AddConstraint(
            model_name='detailedmod',
            constraint=models.UniqueConstraint(fields=('name', 'basemod_ptr'), name='unique_name_per_unique_identifier'),
        ),
    ]
